name: Feature Request
description: Suggest an idea for this project
title: 'FEAT(YYYYMMDD): '
labels: ['feature', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        # 💡 Feature Request Notice

        Thank you for taking the time to file an issue! Please fill out the template below so we can better understand and address your request.

        🔍 **Before submitting**, please search for existing issues or discussions. If there's already one, feel free to add your thoughts there instead of creating a new issue.

        🚀 You're encouraged to start a discussion first and submit a feature request once there's agreement on the idea.

        📚 Refer to [CONTRIBUTING.md](../CONTRIBUTING.md) before making any changes.

  - type: checkboxes
    id: existing-issue
    attributes:
      label: ✅ Check Existing Issues
      description: Confirm that you've checked for similar requests
      options:
        - label: I have searched the existing issues and discussions.
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 📝 Problem Description
      description: Is your feature request related to a specific problem? Please describe what the issue is.
      placeholder: "e.g. It's difficult to access a key feature; A certain workflow is inefficient;..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 🙋 Desired Solution
      description: Clearly describe what you want to see implemented.
      placeholder: "e.g. The UI should include a button for...; The system should support..."
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: 🤔 Alternatives Considered
      description: Describe any alternative solutions or features you’ve considered.

  - type: textarea
    id: additional-context
    attributes:
      label: 📎 Additional Context
      description: Add any other relevant information or screenshots about the feature request here.

  - type: checkboxes
    id: availability
    attributes:
      label: 👀 Are You Willing to Help Implement This?
      options:
        - label: I am willing to implement this feature independently.
        - label: I am willing to implement this feature with help from others.
        - label: I can assist during development but will need help.
        - label: I'm just sharing an idea.

  - type: markdown
    attributes:
      value: |
        🎉 Thank you again for contributing to *KoiPilot* ! We appreciate every piece of feedback 😊